### ISSUE TITLE
improve max campaign size behaviour

### ISSUE THREAD

**Issue by gubuntu** [hotosm/field-campaigner#105]
what is max size of a campaign (i keep getting area too large message and there’s no info in about or how it works)

- communicate to the user that there is a maximum and ideally more or less what it is or how it changes
- explain how to change the campaign size if it is too big
 - restart?
 - edit polygon? (this didn't work for me, it seemed to remember the size of the original polygon)

**Comment by cchristelis** [comment]
# Proposed Solution

The user should be notified as they upload/digitise a too large area. Add a red error text with an explanation below the map widget when this is encountered.

**Comment by dimasciput** [comment]
It was already notified with notification 

![screen shot 2017-06-13 at 9 33 25 am](https://user-images.githubusercontent.com/1979569/27063356-6739eca0-501b-11e7-9335-941d398bccc0.png)

Maybe  changes the notification location?

**Comment by gubuntu** [comment]
The notification is clear (after upload) but some pre-notification would be useful (see OP)

Also it should instruct you what to do thereafter (see OP)

**Comment by meomancer** [comment]
@gubuntu 
Latest code show user error, and on the left-bottom map, there is area size that will be green if ok, and red if not ok.
This error and area size indicator are changed every AOI is changed (from upload or editing manually)

![selection_019](https://user-images.githubusercontent.com/4530905/28350874-1f0beb96-6c76-11e7-8789-776fd1d52f6b.png)
![selection_020](https://user-images.githubusercontent.com/4530905/28350876-1f20e9e2-6c76-11e7-85d6-16b190cad0cb.png)
![selection_021](https://user-images.githubusercontent.com/4530905/28350875-1f11437a-6c76-11e7-8d8c-4491bc85b487.png)

is this ticket already fixed by latest code?

**Comment by gubuntu** [comment]
LGTM

out of interest, how is the acceptable area limit calculated?
