### ISSUE TITLE
Develop wireframes for key views or workflows

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#2]

**Comment by cchristelis** [comment]
<img width="1042" alt="screen shot 2017-05-17 at 10 38 11 am" src="https://cloud.githubusercontent.com/assets/2319504/26145684/a18a56d0-3aed-11e7-91f7-8340fc8bda14.png">

**Comment by cchristelis** [comment]
<img width="1036" alt="screen shot 2017-05-17 at 11 05 12 am" src="https://cloud.githubusercontent.com/assets/2319504/26146527/c53ed0da-3af0-11e7-855c-6cc6b6fbb828.png">
<img width="1036" alt="screen shot 2017-05-17 at 11 05 23 am" src="https://cloud.githubusercontent.com/assets/2319504/26146546/d740397c-3af0-11e7-96cb-fa84fa3adc0d.png">

**Comment by cchristelis** [comment]
The updated maqups:

https://app.moqups.com/tim@kartoza.com/BrPEH1go4v/view/page/ae216298d

**Comment by smit1678** [comment]
@cchristelis Thanks. I also deleted the older comments and dropping in screenshots of the current views from the mockups below. Will follow up with some more questions.  

## Landing page
![](https://api.monosnap.com/rpc/file/download?id=0IvjplEZ8Xv3WvGS48BebEkjyy81vs)

## Manage campaign view
![](https://api.monosnap.com/rpc/file/download?id=W41CHXVV2JZ2flon8LTG7a0OVx1rPa)

## Campaign Dashboard view
![](https://api.monosnap.com/rpc/file/download?id=1zYgfg4zdePoWLRWiBhz9lfCUIhbA7)

**Comment by smit1678** [comment]
@cchristelis @MariaSolovyeva Couple follow up questions regarding current wireframes: 

### Engaging users to start mapping

One thing that I think is missing is how do users who come to the dashboard view start to get involved in the campaign? What is the workflow and interaction to get someone off the dashboard view into mapping? 

### Tracking campaign coverage

What’s the right workflow for updating areas that are covered? Is it automatic or a manual workflow to update? 

### Visuals and layout for quality and error functions on dashboard view

A simple list view doesn’t communicate the information well. Based on the information we want to track, I think there are three main sections of information beyond a map view: 

1. Coverage and engagement
2. Quality
3. Review workflow

From our wiki page write-ups, we initially had four sections of information, but perhaps it could be simplified into three by combining coverage and engagement. The flow down the page could follow these sections: start with overall information + plus a map view of the coverage thus far (heat map or something); then move into visualizing the number of areas that are being covered and the number of users engaging; below that you then have quality and error checking information; and lastly, you have a workflow for reviewing and participating in the error checking.

**Comment by cchristelis** [comment]
Hi @smit1678,

# Engaging users to start mapping

Do you think a progress/completeness concept would draw users in or a time-based concept would be more suited to draw users into engagement?

# Tracking campaign coverage

Initially, the campaign managers will have to upload an SHP file to indicate coverage for a specific time period. We will, however, try and deduce activity based on some automatic process. I'm just not sure what the best approach is. We could use generation of features with a buffer, but I'm not sure if this always makes sense...

# Visuals and layout for quality and error functions on dashboard view

Let's update the function sections to these three:
1. Overview
2. Coverage and engagement
3. Quality and Errors

The workflow for fixing errors and increasing quality is done through `the more info` link at the bottom of the each of the indicators of the `Quality and Errors` section. This makes sense to me since correction is always linked to a specific quality or error indication.

**Comment by cchristelis** [comment]
This issue is related to #22

**Comment by smit1678** [comment]
> Do you think a progress/completeness concept would draw users in or a time-based concept would be more suited to draw users into engagement?

I think I was thinking more about getting people to set up OMK, Maps.Me, or another mobile application so people can start mapping. Related to #17 

> Initially, the campaign managers will have to upload an SHP file to indicate coverage for a specific time period. We will, however, try and deduce activity based on some automatic process. I'm just not sure what the best approach is. We could use generation of features with a buffer, but I'm not sure if this always makes sense...

Agreed that the auto approach may not be possible or always make sense. Can we flesh out the shapefile upload more? What is contained in the shapefile? How will we show the shapefile on the map? Is it a binary view of a polygon within the AOI -- yes/no of whether someone has visited? 

Example of how teams have split up areas (based on admin units): 

![](https://api.monosnap.com/rpc/file/download?id=RYmVakGkQdVtjHg23BrJZ7bn6YmsRV)

> The workflow for fixing errors and increasing quality is done through the more info link at the bottom of the each of the indicators of the Quality and Errors section. This makes sense to me since correction is always linked to a specific quality or error indication.

Ok, curious to know how that interaction will function. My assumption would be that a user that is interested in reviewing or editing quality would rather see all at once, instead of separated by type. Then they can quickly act on everything.

**Comment by MariaSolovyeva** [comment]
# The homepage version 1
The thoughts behind this option were to make the look and feel of a dashboard/app:

- Removed the intro and description
- Added the counters in the top left: number of campaigns and participants involved (these numbers are supposed to change depending on the map view)
- Added two CTA to start a campaign or participate in one
- Added the possibility or the user to 
    - explore the global view
    - make a search on the map
    - use  geolocate me button
- As I understood good, there are two types of campaigns? Current and active? Correct me if I'm wrong

![home2](https://cloud.githubusercontent.com/assets/10400420/26625049/9a3d783a-45fb-11e7-8823-8af914bd1f28.png)

# The homepage version 2
This is the extended version of the first one, more detailed.
All the CTA and other dashboard links are moved to the left sidebar
The map and the campaign table is wide here.
Campaigns have more features:
- Tags
- Completeness progress bar
- Participants
- Action: "see" or "manage" (maybe add "participate"?)
- Anything else important can be added here, like errors count, etc - his is to be discussed
- I removed here the indicators of the campaign type, but they can be added back
Below the table, there is the possibility to add some global functions graphs - this is to be discussed

![home3](https://cloud.githubusercontent.com/assets/10400420/26625348/822d3a4a-45fc-11e7-82ca-b232f8bbd9a4.png)

No active campaigns version

![home-no-campaigns](https://cloud.githubusercontent.com/assets/10400420/26625767/c962584a-45fd-11e7-97eb-56a0eef03358.png)


# The campaign dashboard

- The title, tags and description zone on the top right
- The campaign card with time, participants and CTA
- The map part:
Left block shows the map-related functions, which can be turned on/off on the map, and which are working  as the tab titles for the below-map block, which shows the breakdown of the active function.
- All the not map related functions and graphs are below the map block. - what functions will be here is to be discussed

![campaign2](https://cloud.githubusercontent.com/assets/10400420/26625953/57f2d350-45fe-11e7-8b9a-0ace997f3fd3.png)

**Comment by MariaSolovyeva** [comment]
**Here is the homepage updated after our Zoom chat:**
- Left menu removed
- Geo options moved to the map area
- CTA on the top left
- Geolocation option with colors enabled

![home4](https://cloud.githubusercontent.com/assets/10400420/26786735/3a86859e-4a10-11e7-8a92-86a5d22ebf06.png)
![home4-geolocation](https://cloud.githubusercontent.com/assets/10400420/26786868/a7b03ffc-4a10-11e7-8bd8-16a50398df53.png)

**Comment by meomancer** [comment]
hi @MariaSolovyeva @smit1678 
it seems that on landing page, there is participants & completeness for this
these features are based on api (form overpass) that needs to be called

# solution 1
we could do like saving these data locally after call the api
but it would be make not realtime for these data

# solution 2
we could call api every entering landing page 
but it is not good, because api for overpass is quite take times and how about if we have a lot of campaign?
it could make rendering slow, because of waiting one by one for particaipant, completeness and for every campaigns, and will be stack when calling for big campaign

**Comment by cchristelis** [comment]
@meomaner, i think option 1 is probably better. We don't need these values to be precise. I would even think a daily buffer of the results is ok...

**Comment by meomancer** [comment]
i think i deleted accidentally
------------------------------------------------------------------------------------------------------------
it seems that on landing page, there is participants & completeness for this
these features are based on api (form overpass) that needs to be called

solution 1

we could do like saving these data locally after call the api
but it would be make not realtime for these data

solution 2

we could call api every entering landing page
but it is not good, because api for overpass is quite take times and how about if we have a lot of campaign?
it could make rendering slow, because of waiting one by one for particaipant, completeness and for every campaigns, and will be stack when calling for big campaign

**Comment by dimasciput** [comment]
@cchristelis that means feature completeness should be a required input?

**Comment by cchristelis** [comment]
good point @dimas, maybe we then change feature completeness to fearures mapped, which is something we already have?

**Comment by meomancer** [comment]
i think we could make completeness insight function as required for campaign, and put 'required insights' in form
and load completeness based on that

or maybe we don't need feature completeness in quality function

or maybe it is still there, but user will be warned if no feature completeness is selected?

**Comment by cchristelis** [comment]
@dimasciput, what I mean is instead of having a completeness bar, which is going to be unique to each campaign, we just do a feature count in the place of completeness. Since this is something we anyway do measure...

**Comment by meomancer** [comment]
ok @cchristelis 
but basically it is still insights function (count feature)
because we still to call api from overpass and count it's feature

maybe we need to make specific insight function just for calculating features

what we do for now, for calculating feature is getting feature count from one of insight function

**Comment by cchristelis** [comment]
@meomancer, at this level of granularity, precision is less important, that is why I suggested using only daily updates... I would strongly advise not to try and make these numbers real-time.

**Comment by smit1678** [comment]
For completeness, should we look at the coverage function? That may make more sense in terms of conveying the data correctly. Would that be less resource intense? We could perhaps make the coverage function required as well. 

I agree that the data on the landing page does not need to be precise in terms of real-time. But there will be a disconnect with the number they see on the landing page and the updated number someone sees on the campaign page. If we're not keeping these in sync, I wonder if it's more useful to just cut it from the landing page and put a less resource intense process like coverage on the front.

**Comment by MariaSolovyeva** [comment]
**The Create Campaign page**

It is made as a wizard, as @cchristelis  proposed.
I still have some questions about how it is working the file upload and functions adding, so these steps are not shown.

![createcampaign-1](https://user-images.githubusercontent.com/10400420/26867413-e1e1474e-4b6d-11e7-9054-6ab55f0595b4.png)
![createcampaign-2](https://user-images.githubusercontent.com/10400420/26867415-e1e2daf0-4b6d-11e7-9653-18fb1ea83dd6.png)

**Comment by cchristelis** [comment]
Note:
- It would be great if we could step back/forward to any step once we have passed it.

**Comment by MariaSolovyeva** [comment]
**Campaign Dashboard mobile page**

- Fix the map to the top and make it around 30% of the area below the menu
- Move the sidebar with map-related functions below the vcard, and make it working as an accordion. 

![dashboard-mobile](https://user-images.githubusercontent.com/10400420/26969410-515460ec-4d0e-11e7-9068-b9f04a8f994d.png)

**Comment by MariaSolovyeva** [comment]
hi @dimasciput and @meomancer , I've sent you a letter with some small fixes of the UI :

- Change the main font to Open Sans
- Add the actions buttons/icons to the home table
- Remove the borders from the table

The map search and campaign side panel are not implemented yet, shall we create the separate tickets for them?
