### ISSUE TITLE
Users not showing

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#292]
It's been more than 12 hours since we made edits but users and new edits are not showing up in the campaign dashboard: 

![map campaigner - kamwokya area kampala 2017-08-24 09-45-52](https://user-images.githubusercontent.com/796838/29653144-51d07c8e-88b1-11e7-9377-0f843087295b.png)

To fix this, a new campaign was created that shows the correct number of users: http://campaigns-dev.hotosm.org/campaign/16ca0855f0254d9b9150b4e3fa7253da

**Comment by dimasciput** [comment]
Can you show me the start and end of the date of the campaign?

**Comment by dimasciput** [comment]
I tried to replicate this but couldn't, I tried to edit a node and it shows up couple mins later
![screen shot 2017-08-25 at 3 25 54 pm](https://user-images.githubusercontent.com/1979569/29705771-b65a5988-89a9-11e7-9980-8fa7146463ed.png)

**Comment by smit1678** [comment]
This is the campaign where it isn't showing up: http://campaigns-dev.hotosm.org/campaign/f9b6b31b39204ebca9d6422d2cb167b6. Edits were made on August 23. 

The edits on August 23 show up on this campaign: http://campaigns-dev.hotosm.org/campaign/afe17248406a463884c82b9008b97344. Which is a subset of AOI of the larger campaign.

**Comment by dimasciput** [comment]
@smit1678 I checked directly to overpass, and didn't get any results for that geometry.

**Comment by smit1678** [comment]
@dimasciput Ok, so what's the issue with this geometry then? It's covering the same area.

**Comment by dimasciput** [comment]
Ok I fixed this, this is caused by the polygon gaps after we joined the polygon : 
<img width="641" alt="screen shot 2017-08-26 at 5 10 52 pm" src="https://user-images.githubusercontent.com/1979569/29740519-77481eb8-8a82-11e7-94b3-366a0be90372.png">

And after I remove the gaps, it works
<img width="646" alt="screen shot 2017-08-26 at 5 08 41 pm" src="https://user-images.githubusercontent.com/1979569/29740527-91d141c4-8a82-11e7-967a-d0009f042d89.png">

**Comment by smit1678** [comment]
👍 nice catch. Deployed and it's working on http://campaigns-dev.hotosm.org/, looks like this problem was causing other campaigns to show no users as well but I didn't realize that.
