### ISSUE TITLE
Better Styling of Mapped Features

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#357]
# Problem

We would like to show the quality of the mapped features. This could by assigning colours on a colour ramp based on completeness. Dark green perfect, yellow one error ... Red.

# Proposed Solution

Get an adaptable range between no attributes collected and all collected and style the features accordingly.

**Comment by PaulUithol** [comment]
(this is about the campaign view, display of features on the map)

**Comment by meomancer** [comment]
hi @cchristelis 
do you mean that if we check (based on tags)
```
name, operating_hours, location
```
so the color would be like:
- if all present : dark green
- if name miss : yellow
- if name and location miss : dark yellow
- if all miss : red

something like this?
and because of tags number can vary for each other, can be more than 3, we need some function to define color range for number of tags, isn't it?

**Comment by PaulUithol** [comment]
Roughly like that, yes! Please do pick colors/hues that are contrasting
with both the map color, and the team/coverage colors (assigned, visited
etc). Hand picked may be better than a function, so we can check how colors
combine.

As the number of keys/tags requested grows though, the colors will get
closer together and less distinct, so let's limit to 5 or 6 colors max, and
combine different numbers of tags missing in 1 color.

That way, you should still be able to visually pick out those that are
fully correct from those missing 1 tag for example, which is important. But
it's fine if, say, 6 and 7 keys missing are the same color, that's not a
difference I'd care about.

~ sent from mobile

On Sep 26, 2017 08:56, "Irwan Fathurrahman" <notifications@github.com>
wrote:

hi @cchristelis <https://github.com/cchristelis>
do you mean that if we check (based on tags)

name, operating_hours, location

so the color would be like:

   - if all present : dark green
   - if name miss : yellow
   - if name and location miss : dark yellow
   - if all miss : red

something like this?
and because of tags number can vary for each other, can be more than 3, we
need some function to define color range for number of tags, isn't it?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/hotosm/field-campaigner/issues/357#issuecomment-332104451>,
or mute the thread
