### ISSUE TITLE
Difference between fields in the Add Custom Type

### ISSUE THREAD

**Issue by smit1678** [hotosm/field-campaigner#376]
@cchristelis @dimasciput Can you explain the difference between the fields for the Add Custom Type modal? 

When filling in the following: 
  * Name: Parking Lots
  * Feature: amenity=parking
  * Tags: amenity=parking

This does not work. The modal closes but when you submit to save the campaign, the app errors and does not proceed. 

Also, do we need to have at least one tag required for simple tags like this?

**Comment by meomancer** [comment]
hi @smit1678 
i will check it why the app errors with this fields

here is the difference
- Name is the name of type
- Feature is the feature that will be check, what i mean is if amenity=parking, it will get data that just amenity=parking
- tags is used for check completeness, so, if we fill amenity=parking, it will tell to check if it has amenity and amenity value is parking

and also, why need at least one tag? because custom tags doesn't have predefined, so if we don't give tags to be check, it will just show all feature as complete, because it doesn't check anything.

Maybe my suggestions is:
- when we fill feature, it will automatically add one tags same as feature

**Comment by smit1678** [comment]
> Maybe my suggestions is: when we fill feature, it will automatically add one tags same as feature

👍  yeah that makes sense to me.
