### ISSUE TITLE
Styling: Use consistent link style, only use buttons for buttons

### ISSUE THREAD

**Issue by tordans** [hotosm/field-campaigner#407]
I looked at http://campaigns.hotosm.org/campaign/bc98b1f4d73c4b3fb2cc29c7bc5633b4 for the first time and was confused by what I can click and whats an information.

A few suggestions to clarify this interaction:

**a. Use a consistent link style**
ATM you the dark orange as a link style. But also as a highlighting color. 
In other places, important parts of the page are clickable but dont use the link style.
And then there is this third link style in blue…

**b. Don't use button style where there is no button**
I guess this is not be a game of hide and seek where a user needs to click elements to discover if they are a link :). So elements that are not buttons should not use the button style. Mainly "Participate" and  "Share".

**c. Reduce visual complexity**
For example the italic font style does not help understand the structure but only makes it more complex visually.

## Suggestion for a:
My suggestions about link (and button) styles

![screencapture-campaigns-hotosm-org-campaign-bc98b1f4d73c4b3fb2cc29c7bc5633b4-1515221325061](https://user-images.githubusercontent.com/111561/34637463-b222babe-f2b7-11e7-9a36-4fafb4a16990.png)
[Full image](https://user-images.githubusercontent.com/111561/34637463-b222babe-f2b7-11e7-9a36-4fafb4a16990.png)

## Screenshot for b
Why not just use the label-button pattern for here. A quick mockup below.
Also, the share could move over to the "Participate" row so save space. It also belongs there, since its just another way to "participate".

BEFORE
<img width="1396" alt="bildschirmfoto 2018-01-06 um 07 41 20" src="https://user-images.githubusercontent.com/111561/34637482-3d6f2abc-f2b8-11e7-9946-b97097440359.png">

AFTER
(The "share" should also be a label)
For HTML with inline forms and labels check https://getbootstrap.com/docs/3.3/css/#forms-inline
<img width="1399" alt="bildschirmfoto 2018-01-06 um 07 41 13" src="https://user-images.githubusercontent.com/111561/34637483-3d86b984-f2b8-11e7-8302-695061710ded.png">

## Screenshot for c
Removing the italic is a good step.

<img width="1317" alt="bildschirmfoto 2018-01-06 um 07 29 43" src="https://user-images.githubusercontent.com/111561/34637498-6844dcaa-f2b8-11e7-8b47-d04944611633.png">

**Comment by smit1678** [comment]
@tordans I like the suggestions here. Agreed that there needs to be some better link consistency across the pages. I had been just starting to take a look at some of these same things last week to do some clean up ([notes from my review with Amelia Hunt](https://gist.github.com/smit1678/7469e58411b289260a3469a4ea802d02)). I just put up #408 with some initial adjustments that I finished last week - mostly text but a few other clean up items. 

> Screenshot for b

👍  I like that proposal because it moves the share buttons into more of the participate section.

> Removing the italic is a good step.

👍 

Since I'm doing some work on it today, I can probably tackle B and C. 

@tordans Would you be interested in working on proposing some improvements for A? Not sure if you're in a position to do some work on this, if not, we can break these out into some individual tickets that we can address going forward.
