### ISSUE TITLE
Landing Page - I don't see capaigns

### ISSUE THREAD

**Issue by cchristelis** [hotosm/field-campaigner#508]
# Problem

When I'm not logged in I don't see the campaigns on the landing page.

# Proposed Solution

Allow anonymous users to see campaigns.

**Comment by pierrealixt** [comment]
It works.
![Capture d’écran 2018-09-06 à 08.34.26.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b30a1407a567800129bc06d/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b371f2122d410ea3febc41504147f8e78b2db4aa2e30c80351b882294d7ed43819f9bcd049ba54be24dd48d0bfbc8a44c8e83b2ce2d98b5d220c4749d7ab0268f9d31e8a4afc59e0445fa5163565e477337a4e95167d2b792a.png)


You're still half-right though, half of the time, there is a 500 error while fetching the campaigns. 
It happens when I choose to display the nearest campaigns.
![Capture d’écran 2018-09-06 à 08.39.34.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b30a1407a567800129bc06d/125516c66e82c728ace21e0d46cb958a379791accfed3da35d585c752a54267d6956f37a28c8b371f2122d410ea3febc41504147f5e78a2fb4aa2e30c80351b882294d7ed43819f9bcd049ba54be24dd48d0bfbc8a44c8e83b2ce2d98b5d220c4749d7ab0268f9d31e8a4afc59e34d5fa5163565e477307c45971c7724792a.png)

But it has nothing to do with being an anonymous users.

There is as well a performance issue I must investigate. It lists the campaigns (in S3) and fetch, open, read every campaign.json and returns only the active or inactive, or nearest.
